export const ItemEndpoint = 'api/v1/item'
export const CategoryEndpoint = 'api/v1/categories'
export const UserEndpoint = 'api/v1/users'
export const LoginEndpoint = 'api/v1/auth/login'
export const RegisterEndpoint = 'api/v1/auth/register'
export const LogoutEndpoint = 'api/v1/auth/logout'